version: "3.7"

# Service Definitions
services:

  app:
    environment:
      CACHE_VIEWS: "false"
      NODE_ENV: "development" # auto-reloads app on save, dev builds
    # WEBPACK_HMR: "true" # default is false -- this is useful for when you're focused on Frontend Dev
    ports:
      - "8080:8080" # adonis http port
      - "8081:8081" # webpack-dev-server port
    volumes:
      - ./app/myapp:/app


secrets:
  adonis.appkey:
    external: false
    file: ./docker-secrets/adonis.appkey.v1